services:
  backend:
    build: backend
    restart: always
    networks:
      - react-spring
    healthcheck:
      test: "curl --fail --silent localhost:8080/actuator/health/readiness | grep UP || exit 1"
      interval: 2s
      timeout: 3s
      retries: 5
      start_period: 2s
    ports:
      - 8080:8080

  frontend:
    build:
      context: frontend
    ports:
      - 3000:80
    volumes:
      - /project/node_modules
    networks:
      - react-spring
    depends_on:
      - backend

networks:
  react-spring: {}
